/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5c7f879a568681581952d157
*
* You will get 10% discount for each one of your friends
* 
*/
/**

  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
                                                                                     
                                                                                   
 *  DO NOT EDIT HIS FILE!!
 * 
 *  FOR CUSTOMIZE DB SCHEMA PLEASE EDIT db/Prova_Prato_db_customSchema.js
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 * 
 */

const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const createUser = require('../security/security.js');

const db_Prova_Prato_db_schema = [];
const db_Prova_Prato_db = [];

/**
 * SCHEMA DB Prova_Prato_db
 */



 /**
  * Comuni
  */
db_Prova_Prato_db_schema.Comuni = new mongoose.Schema({
	cod_comune: {
		type: 'Number', 
		required : true
	},
	cod_rip_geo: {
		type: 'Number'
	},
	denom_reg: {
		type: 'String'
	},
	rip_geo: {
		type: 'String'
	},
	//RELATIONS
	relcom: {
		type: Schema.ObjectId, 
		required : true,
		ref : "Desc_Comuni"
	},
	
	
	//EXTERNAL RELATIONS
	/*
	*/
});


 /**
  * Desc_Comuni
  */
db_Prova_Prato_db_schema.Desc_Comuni = new mongoose.Schema({
	cod_catast: {
		type: 'String'
	},
	cod_comune: {
		type: 'Number', 
		required : true
	},
	denom_comu: {
		type: 'String'
	},
	popolazione: {
		type: 'Number'
	},
	sigla: {
		type: 'String'
	},
	//RELATIONS
	
	
	//EXTERNAL RELATIONS
	/*
	relcom: {
		type: Schema.ObjectId, 
		required : true,
		ref : "Comuni"
	},
	*/
});



// Import schema customization
require('./Prova_Prato_db_customSchema.js');
var Prova_Prato_db_model = require('./Prova_Prato_db_crud.js');

// Declare mongoose model

db_Prova_Prato_db.Comuni = Prova_Prato_db_model.connection.model('Comuni', db_Prova_Prato_db_schema.Comuni );
db_Prova_Prato_db.Desc_Comuni = Prova_Prato_db_model.connection.model('Desc_Comuni', db_Prova_Prato_db_schema.Desc_Comuni );

module.exports = db_Prova_Prato_db;

// Create ADMIN user if does not exist
createUser.createUser();
